jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Python script with secret key
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        python test.py

